### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by LeeCharry** [wjbd/fish_redux_demo#1]
错误信息：
Compiler message:
/C:/Users/dev&keep/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio-2.1.13/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/Users/dev&keep/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio-2.1.13/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^

Compiler message:
/C:/Users/dev&keep/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio-2.1.13/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/Users/dev&keep/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio-2.1.13/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by wjbd** [comment]
没发现上面的问题，跟代码有什么关系，可以尝试flutter clean一下，然后在运行
